# Generated by Django 2.2.1 on 2019-09-29 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Buyer.PayOrder'),
            preserve_default=False,
        ),
    ]
