# Generated by Django 2.2.1 on 2019-09-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0004_cart_cart_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_status',
        ),
        migrations.AddField(
            model_name='cart',
            name='order_number',
            field=models.CharField(default=0, max_length=32),
        ),
    ]
