# Generated by Django 2.2.1 on 2019-09-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Saller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
